version: '3.7'

services:
  tmsapp_cn:
    volumes:
      - static:/static
    build:
      context: .
    env_file:
      - ./tmsapp/tmsapp/settings/.env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - tmsapp_cn    

volumes:
  static:
